.github/NEW_TICKET.yml
Add `needs-response` automatically to all new tickets.
=> Automatically label new tickets

c3r-cli/src/main/java/com/amazonaws/c3r/cleanrooms/CleanRoomsDao.java, c3r-cli/src/main/java/com/amazonaws/c3r/cli/EncryptMode.java, c3r-cli/src/main/java/com/amazonaws/c3r/cli/SchemaMode.java, c3r-cli/src/main/java/com/amazonaws/c3r/io/schema/CsvSchemaGenerator.java, c3r-cli/src/main/java/com/amazonaws/c3r/io/schema/InteractiveSchemaGenerator.java, c3r-cli/src/main/java/com/amazonaws/c3r/io/schema/ParquetSchemaGenerator.java, c3r-cli/src/main/java/com/amazonaws/c3r/io/schema/SchemaGenerator.java, c3r-cli/src/main/java/com/amazonaws/c3r/io/schema/SchemaGeneratorUtils.java, c3r-cli/src/main/java/com/amazonaws/c3r/io/schema/TemplateSchemaGenerator.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/MainErrorMessageTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/MainTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/SchemaCliConfigTestUtility.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/SchemaModeArgsTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/SchemaModeTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/io/schema/InteractiveSchemaGeneratorTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/io/schema/ParquetSchemaGeneratorTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/io/schema/TemplateSchemaGeneratorTest.java, c3r-sdk-core/src/main/java/com/amazonaws/c3r/io/CsvRowReader.java, c3r-sdk-parquet/src/test/java/com/amazonaws/c3r/data/ParquetDataTypeTest.java, c3r-sdk-parquet/src/test/java/com/amazonaws/c3r/io/ParquetRowReaderTest.java
N/A
Schema generation modes can take an optional
collaboration ID at the CLI, which the client will 
use to fetch cryptographic computing settings and
appropriately limit/guide schema generation.
=> add optional collab id for schema gen

.github/workflows/repo-sync.yml
- Adds a workflow for syncing the `main` branch of forks automatically at midnight each day.
- Workflow may also be run manually from the GitHub UI.
=> Add repo sync workflow for forks.

.github/workflows/gradle-build-ci.yml, .github/workflows/jacoco.yml
- Added filters for gradle-build-ci and jacoco to only run if changes were made to:
- any file in any `src` directory
- any files in the `samples` directory
- any files in the `config` directory,
- any `.gradle` files. 
- The file filtering above scales to support new packages automatically instead of just adding exemptions on different file types or stating explicitly which src/gradle files to watch for.
- Added filter for jacoco to skip if it has already run for the same commit.
=> Add filters for gradle-build-ci and jacoco GHAs

c3r-sdk-core/build.gradle, c3r-sdk-core/src/main/java/com/amazonaws/c3r/action/CsvRowMarshaller.java, c3r-sdk-core/src/test/java/com/amazonaws/c3r/action/CsvRowMarshallerTest.java
- Add a validation step for the CsvRowMarshaller to give a warning if users have provided a custom null value for the output, but the output has no cleartext columns where the value would be used.
=> Warn on custom null when no cleartext targets

c3r-cli/src/main/java/com/amazonaws/c3r/cleanrooms/CleanRoomsDao.java, c3r-cli/src/test/java/com/amazonaws/c3r/cleanrooms/CleanRoomsDaoTest.java
Display error message content from AWS SDK exceptions to aid user debugging
since they contain no sensitive information from the input file or schema.
For example, now errors regarding AWS_REGION not being set are printed to the user by default:
```
C3R_SHARED_SECRET="vLO8H9rCFs4FO9b+K9xGERL1IhtgJBhe9OV5EXAMPLE=" \ 
java -jar c3r-cli/build/libs/c3r-cli-all.jar \
encrypt \
samples/csv/data_sample_no_headers.csv \
--schema=samples/schema/config_sample.json \
--id=123e4567-e89b-12d3-a456-426614174000 \
--output=output.csv \
--overwrite
[ERROR]: An error occurred: Unable to connect to AWS Clean Rooms: Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@163d04ff …
```
=> display messages from AWS SdkExceptions

c3r-cli/src/main/java/com/amazonaws/c3r/io/schema/InteractiveSchemaGenerator.java
Improve max padding description in interactive schema generation.
Old prompt
```
Byte-length beyond max length to pad cleartext to in `COLUMN_NAME` (default `0`)?
```
New prompt
```
All values in `COLUMN_NAME` will be padded to the byte-length of the
longest value plus a specified number of additional padding bytes.
How many additional padding bytes should be used (default `0`)?
```
=> more detailed max padding description

c3r-cli/src/main/java/com/amazonaws/c3r/cleanrooms/CleanRoomsDao.java, c3r-cli/src/test/java/com/amazonaws/c3r/cleanrooms/CleanRoomsDaoTest.java
Allow custom creation of CleanRoomsClients for CleanRoomsDao objects.
Makes testing in more environments easier, since we can prompt an SDK fail
no matter how hard the SDK tries to find valid settings locally on the system
under test.
=> add param for CleanRoomsDao client creation

README.md, c3r-cli/src/main/java/com/amazonaws/c3r/cleanrooms/CleanRoomsDao.java, c3r-cli/src/main/java/com/amazonaws/c3r/cli/CliDescriptions.java, c3r-cli/src/main/java/com/amazonaws/c3r/cli/EncryptMode.java, c3r-cli/src/main/java/com/amazonaws/c3r/cli/SchemaMode.java, c3r-cli/src/test/java/com/amazonaws/c3r/cleanrooms/CleanRoomsDaoTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/cleanrooms/CleanRoomsDaoTestUtility.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/CliTestUtility.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/EncryptCliConfigTestUtility.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/EncryptModeArgsTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/MainCsvSingleRowRoundTripTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/MainEnvVarKeyValidTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/MainErrorMessageTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/MainPerfTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/MainTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/SchemaCliConfigTestUtility.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/SchemaModeArgsTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/SchemaModeTest.java
Add --profile and --region flags to encrypt and schema
modes to support convenient usage of AWS CLI named
profiles and region selection. Also more testing generally
around how our code makes contact with the AWS SDK
for making AWS Clean Rooms API calls.
=> add --profile and --region CLI flags

c3r-cli/build.gradle, c3r-cli/src/main/java/com/amazonaws/c3r/cli/DecryptMode.java, c3r-cli/src/main/java/com/amazonaws/c3r/cli/EncryptMode.java, c3r-cli/src/main/java/com/amazonaws/c3r/cli/SchemaMode.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/DecryptModeDryRunTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/EncryptModeDryRunTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/MainArgParseTest.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/SchemaModeDryRunTest.java
Fix some minor bugs in optional and required arg parsing.
Rename *ModeArgTest => *ModeDryRunTest to emphasize
those classes check behavior equivalent to running each mode
with the `--dryRun` flag, while the new `MainArgParseTest`
class test only CLI parameter parsing and rules PicoCLI
is being leveraged to enforce.
=> Fix CLI arg parsing bugs

config/checkstyle/checkstyle.xml
The ignore line clause in the copyright checkstyle rule does not apply to our copyright header (i.e., it features no date or other content that changes). Removing this allows checkstyle to validate the whole copyright in each file.
=> drop ignores from copyright checkstyle rule

.github/workflows/gradle-build-ci.yml, .github/workflows/jacoco.yml, c3r-cli/build.gradle, c3r-sdk-core/build.gradle
- Revert bump to gradle 8.0.1 and the shadow package to 8.1.0
=> Revert Gradle version bump to unblock CodeBuild

c3r-sdk-core/src/main/java/com/amazonaws/c3r/io/CsvRowReader.java, c3r-sdk-core/src/test/java/com/amazonaws/c3r/io/CsvRowReaderTest.java, samples/csv/one_row_too_few_columns.csv, samples/csv/one_row_too_many_columns.csv
- Previously, varying column counts were being permitted for CSVs. Extra columns would be trimmed or missing columns substituted as empty values . But, given the nature of CSVs and not knowing if the additional/missing columns came at the tail of the line or somewhere before, it's prudent to fail and consider it a malformed CSV.
=> Validate that CSV column counts are as expected

c3r-cli/src/main/java/com/amazonaws/c3r/cli/Main.java, c3r-cli/src/test/java/com/amazonaws/c3r/cli/MainErrorMessageTest.java
- Adds a final warning message to the user in the event of a terminal error that output files may have been left on disk.
```
19:47:04.223 [Test worker] ERROR com.amazonaws.c3r.cli.Main - An error occurred: Cannot read from file `/tmp/temp10460064972614849108/missingSchemaValidateIllegalArgument.csv`. File does not exist.
com.amazonaws.c3r.exception.C3rIllegalArgumentException: Cannot read from file `/tmp/temp10460064972614849108/missingSchemaValidateIllegalArgument.csv`. File does not exist.
at com.amazonaws.c3r.utils.FileUtil.verifyReadableFile(FileUtil.java:92)
at com.amazonaws.c3r.io.schema.SchemaGenerator.validate(SchemaGenerator.java:76)
at com.amazonaws.c3r.io.schema.SchemaGenerator.<init>(SchemaGenerator.java:65)
at …
```
=> Add a final warning that files may have been left on disk.

.github/workflows/gradle-build-ci.yml, c3r-sdk-examples/build.gradle, c3r-sdk-examples/src/main/java/com/amazonaws/c3r/examples/spark/SparkExample.java, c3r-sdk-examples/src/main/java/com/amazonaws/c3r/examples/spark/package-info.java, c3r-sdk-examples/src/test/java/com/amazonaws/c3r/examples/spark/SparkExampleTest.java
- Adds an example of Spark orchestrating the CLI so that those that need to process big data can benefit from Spark's parallelization capabilities.
- Bumps the CI version of Hadoop from 3.2.2 to 3.3.1
- Switches the Hadoop repo used for CI from `cdarlint` to `kontext-text`, which took over after the Hadoop 3.2.2 release
=> Spark Example

.github/dependabot.yml, .github/workflows/pr-lint.yml
- Adds linting to PR titles to enforce the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/).
- Updates Dependabot to use Conventional Commit specs for its own PRs.
- Adds a timestamp to when Dependabot runs to help avoid repo sync errors
=> ci: Add Conventional Commit PR enforcement

build.gradle, c3r-cli/build.gradle, c3r-sdk-core/build.gradle, c3r-sdk-examples/build.gradle, c3r-sdk-parquet/build.gradle
- Some of our dependencies need to be kept in sync (hadoop/spark/freefair/etc). Dependabot doesn't update more than one at a time unless the version is parameterized.
- Consolidates `gradle.build` file similarities
- Migrates versions that are coupled to parameters
- Based on behavior mentioned in the comments here: https://github.com/dependabot/dependabot-core/issues/1618
=> refactor: Consolidate versions and gradle builds

c3r-sdk-core/src/test/java/com/amazonaws/c3r/config/EncryptConfigTest.java
- The test was always comparing the final results against itself by using the same output file and the overwrite flags. This changes it to use different output files.
=> test: Fix test to not overwrite the data it was comparing.

c3r-sdk-core/src/main/java/com/amazonaws/c3r/Transformer.java, c3r-sdk-core/src/main/java/com/amazonaws/c3r/action/CsvRowMarshaller.java, c3r-sdk-core/src/main/java/com/amazonaws/c3r/action/CsvRowUnmarshaller.java, c3r-sdk-core/src/main/java/com/amazonaws/c3r/config/Config.java, c3r-sdk-core/src/main/java/com/amazonaws/c3r/config/DecryptConfig.java, c3r-sdk-core/src/main/java/com/amazonaws/c3r/config/EncryptConfig.java, c3r-sdk-parquet/src/main/java/com/amazonaws/c3r/action/ParquetRowMarshaller.java, c3r-sdk-parquet/src/main/java/com/amazonaws/c3r/action/ParquetRowUnmarshaller.java
- Marks the transformer field in Config classes as deprecated.
- Store the SecretKey and Salt in the Config objects.
- Adds helper methods for `Transformer.initTransformers` that take Config objects.
=> refactor: Deprecate config transformers

.github/workflows/gradle-build-ci.yml
- Reduces Gradle CI to only run on PRs to any branch or pushes to main.
=> ci: Gradle build CI run reduction

c3r-cli/src/main/java/com/amazonaws/c3r/io/schema/InteractiveSchemaGenerator.java, c3r-sdk-core/src/main/java/com/amazonaws/c3r/config/TableSchema.java, c3r-sdk-core/src/main/java/com/amazonaws/c3r/internal/Limits.java, c3r-sdk-core/src/main/java/com/amazonaws/c3r/io/CsvRowReader.java, c3r-sdk-core/src/test/java/com/amazonaws/c3r/config/TableSchemaTest.java, c3r-sdk-parquet/src/main/java/com/amazonaws/c3r/io/ParquetRowReader.java, c3r-sdk-parquet/src/test/java/com/amazonaws/c3r/io/ParquetRowReaderTest.java
- This changes the input column limit of 1600 to be 10,000.
- The original column limit of 1600 is now enforced on the output instead of the crypto limit of 2^31.
=> fix: Change input/output column count limits

c3r-cli/src/test/java/com/amazonaws/c3r/io/schema/InteractiveSchemaGeneratorTest.java, c3r-sdk-core/src/main/java/com/amazonaws/c3r/config/ColumnHeader.java, c3r-sdk-core/src/main/java/com/amazonaws/c3r/internal/Limits.java, c3r-sdk-core/src/test/java/com/amazonaws/c3r/config/ColumnHeaderTest.java, c3r-sdk-core/src/test/java/com/amazonaws/c3r/io/CsvRowReaderTest.java, c3r-sdk-core/src/test/java/com/amazonaws/c3r/io/sql/TableGeneratorTest.java
+ Deprecate Glue header limits
+ Use Clean Rooms header limits
+ Precompile the regexp expression for efficient matching
+ Change single-row test headers to not include a backslash (violates new restrictions)
=> fix: use Clean Rooms header limits, not Glue

c3r-cli-spark/src/integration-test/spark_integration_tests.py, codebuild/build-and-test-release-artifacts.sh
+ Add a spark_integration_tests.py script based on the standard
integration_tests.py which downloads Spark, sets up a server, and runs a few tests with the `c3r-cli-spark` JAR
+ Update Codebuild CI build+test script (build-and-test-release-artifacts.sh) to now also run the Spark integration tests (this will mean they're incorporated into both the nightly CI and release scripts).
=> test(spark): spark integration tests

c3r-cli-spark/src/test/java/com/amazonaws/c3r/spark/action/SparkMarshallerTest.java, c3r-cli-spark/src/test/java/com/amazonaws/c3r/spark/io/csv/SparkCsvReaderTest.java, c3r-cli-spark/src/test/java/com/amazonaws/c3r/spark/io/parquet/SparkParquetReaderTest.java
- There is a grey area around how Spark handles SQL. Normally, SQL is escaped in accordance with the SQL driver being used. Spark does not provide the same SQL injection protections that other languages do since the underlying SQL driver may not be known. 
- For a ColumnHeader to be constructed, it must have a value that matches `[a-z0-9_](([a-z0-9_ ]+-)*([a-z0-9_ ]+))?`
- Our custom CSV reader will fail trying to turn any malicious columns into a ColumnHeader.
- Spark's Parquet reader will permit a malicious value, but the value will be dropped before we ever construct SQL queries when we run `SparkMarshaller.filterSourceColumnsBySchema`.
- If a malicious header were in the dataset somehow and made it past the filtering, our two methods …
=> test(spark): Add validations to for malicious column headers in source files

.github/workflows/gradle-build-ci.yml
The gradle-no-failures CI job will pass if no build job failed (i.e., all build jobs succeeded or were skipped due to being a duplicate build that already succeeded).
This should allow us to block PR merging in a way that is compatible with our usage of the `fkirc/skip-duplicate-actions` action, which skips a build if it has succeeded elsewhere in CI. Previously the skipping of previously successful build jobs interfered with making the build jobs required to merge. This new job alleviates that problem by letting it be the blocking action instead of the (possibly skipped) build jobs themselves.
=> ci: add a job gradle-no-failures to aggregate all build job results

c3r-cli-spark/src/integration-test/spark_integration_tests.py
Pin spark client integration tests to 3.4.1 and not the latest release, since the client is not always compatible with the latest release (e.g., between when the new release drops and the client get's any needed changes to adapt).
=> ci: pin spark integration tests to 3.4.1, not latest release

.github/workflows/gradle-build-ci.yml
Set our standard CI build to a nightly schedule as a layer of defense to ensure any pushes to `main`---even those from dependabot---are built and have their result registered with the associated github action.
=> ci: set ci build to run nightly

build.gradle, c3r-cli-spark/build.gradle, c3r-cli-spark/src/main/java/com/amazonaws/c3r/spark/action/SparkMarshaller.java, c3r-cli-spark/src/main/java/com/amazonaws/c3r/spark/action/SparkUnmarshaller.java, c3r-cli/build.gradle, c3r-sdk-core/build.gradle, c3r-sdk-examples/build.gradle, c3r-sdk-examples/src/main/java/com/amazonaws/c3r/examples/spark/SparkExample.java, c3r-sdk-parquet/build.gradle
- Fixes the use of RowEncoder.apply to be ExpressionEncoder.apply in order to update from Spark 3.4.1 to 3.5.0
- Moves spotbugs to a variable in the main gradle build file for clean up
=> build(gradle): Bump spark_version from 3.4.1 to 3.5.0

.github/dependabot.yml
- Locks spotbugs until the update can be dealt with.
=> ci: Locks spotbugs until the merge conflicts with it may be dealt with

c3r-sdk-core/src/main/java/com/amazonaws/c3r/data/ClientValueWithMetadata.java, c3r-sdk-core/src/main/java/com/amazonaws/c3r/data/Units.java, c3r-sdk-core/src/main/java/com/amazonaws/c3r/data/ValueConverter.java, c3r-sdk-core/src/test/java/com/amazonaws/c3r/data/ClientDataTypeMetadataTest.java, c3r-sdk-core/src/test/java/com/amazonaws/c3r/data/UnitsTest.java, c3r-sdk-core/src/test/java/com/amazonaws/c3r/data/ValueConverterTest.java
The encoders and decoders that need metadata beyond what is in `ClientDataInfo` (i.e., scale and precision for Decimal)
=> feat: Encoders/Decoders with Metadata

c3r-sdk-core/src/main/java/com/amazonaws/c3r/data/ValueConverter.java, c3r-sdk-core/src/test/java/com/amazonaws/c3r/data/ValueConverterTest.java
Change `char[]` to `String` so UTF-8 is used for character based values (makes `CHAR`, `STRING` and `VARCHAR` a valid equivalence class too that way). Also some minor cleanup of code and tests so common functionality is pulled into some common parametrised tests.
=> fix: Make all encoded string types use utf-8 encoding

c3r-cli-spark/src/integration-test/spark_integration_tests.py
This reverts commit 106f49bceba56b4eed5941744cab9e92363bd544.
=> test: revert "ci: pin spark integration tests to 3.4.1, not latest release (#357)"

c3r-cli-spark/src/integration-test/spark_integration_tests.py
- Locks the version of Spark used for integration tests to 3.5.1. Version 4 is currently in preview and has not yet been evaluated.
=> chore: lock spark version in spark integ tests to version 3.5.1.

.gitignore, c3r-cli-spark/src/integration-test/spark_integration_tests.py, codebuild/build-and-test-release-artifacts.sh
- Bumps Hadoop from 3.5.1 to 3.5.3 for CodeBuild runs.
- Fixes CodeBuild script grabbing logs along with the version of C3R when Log4j is noisy.
=> build: Bump CodeBuild Spark version and fix script

README.md
- Adds a FAQ pointing to how customers may configure C3R to use FIPS endpoints when communicating with AWS.
=> docs: Add a FAQ about using FIPS with C3R.

.github/workflows/gradle-build-ci.yml, .github/workflows/jacoco.yml, build.gradle
- Migrate from older `gradle-build-action` to replacement `setup-gradle`
=> ci: Switch Gradle Build action from gradle-build-action to setup-gradle
