aws/c3r

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/new_ticket.yml
=> Move file to right location

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, SECURITY.md
- Updates to templates to match current guidance: https://github.com/aws/.github
=> Update to match current templates provided by github.com/aws/.github

c3r-sdk-core/build.gradle, c3r-sdk-parquet/build.gradle
N/A
Update maven-related gradle build configurations for SDK modules.
=> gradle maven-related updates

.github/workflows/dependabot-auto-merge.yml
- Automates approving and merging dependabot updates.
=> Dependabot automation

c3r-cli/src/test/java/com/amazonaws/c3r/io/CsvTestUtility.java, c3r-sdk-core/src/test/java/com/amazonaws/c3r/action/RowMarshallerTest.java, c3r-sdk-core/src/test/java/com/amazonaws/c3r/io/CsvTestUtility.java
Reduces some duplicate, unneeded code from the test suite.
=> trim down unneeded code in test helpers

c3r-sdk-core/src/test/java/com/amazonaws/c3r/config/TableSchemaTest.java
Add utility function to set up mocks for TableShemas. For now, only in the file it's needed.
=> Add utility function to set up mocks for TableShemas.

.github/workflows/gradle-build-ci.yml, .github/workflows/jacoco.yml, c3r-sdk-core/build.gradle
- Bump Gradle from 7.5.1 -> 8.0.1
=> Gradle ci version

CHANGELOG.md, c3r-cli/src/main/java/com/amazonaws/c3r/cli/CliDescriptions.java, c3r-sdk-core/build.gradle, c3r-sdk-parquet/build.gradle
- Bump C3R from 1.0.0 to 1.1.0
=> Release Version 1.1.0

README.md
Simplify a few sentences, introduce SDK abbreviation initially.
=> docs: simplify a few README sentences

c3r-sdk-examples/src/main/resources/log4j2.xml, c3r-sdk-examples/src/test/resources/log4j2.xml, config/checkstyle/checkstyle.xml
…ttings.
- Log4j settings will reduce noise of Spark libraries
- Checkstyle changes improve the ability to exempt certain items from meeting Checkstyle
=> Add Log4j and Update Checkstyle Exemption Settings

c3r-sdk-core/build.gradle, c3r-sdk-parquet/build.gradle
- Update the Maven publishing plugin to properly include the dependencies in the POM.
Before:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
<script/>
<modelVersion>4.0.0</modelVersion>
<groupId>software.amazon.c3r</groupId>
<artifactId>c3r-sdk-parquet</artifactId>
<version>1.1.0</version>
<name>Amazon C3R SDK Parquet</name>
<description>Cryptographic Computing for Clean Rooms SDK Parquet Support</description>
<url>https://github.com/aws/c3r</url>
<inceptionYear>2022</inceptionYear>
<licenses>
<license>
<name>The Apache License, Version 2.0</name> …
```
=> Maven POM Fix

CHANGELOG.md, c3r-cli/src/main/java/com/amazonaws/c3r/cli/CliDescriptions.java, c3r-sdk-core/build.gradle, c3r-sdk-parquet/build.gradle
- Bump C3R from 1.1.0 to 1.1.1
=> Release Version 1.1.1

CHANGELOG.md, c3r-cli/src/main/java/com/amazonaws/c3r/cli/CliDescriptions.java, c3r-sdk-core/build.gradle, c3r-sdk-parquet/build.gradle
Roll version to `1.1.2` and update changelog.
=> docs: Update version number and changelog for release 1.1.2 (#265)

README.md
N/A
+ Add a table of contents to the README
+ Some slight README section tweaks (order and/or section name) motivated by how things looked with the addition of the table of contents
+ Use consistent named-section-links to the user guide throughout
=> docs(readme): add toc, some content reorg, consistent links (#258)

CHANGELOG.md, c3r-cli/src/main/java/com/amazonaws/c3r/cli/CliDescriptions.java, c3r-sdk-core/build.gradle, c3r-sdk-parquet/build.gradle
=> chore: version bump 1.1.2 => 1.1.3 with CHANGLOG.md entries

.github/workflows/gradle-build-ci.yml
Bump gradle/gradle-build-action version to the latest.
=> ci: update gradle-build-ci.yml version

codebuild/build-and-test-release-artifacts.sh
+ Add Spark JAR to build script for testing and release
=> ci: update build script to include spark JAR

.github/workflows/gradle-build-ci.yml
=> ci: gradle-build-ci use --parallel

.github/ISSUE_TEMPLATE.md, SUPPORT.md
- Add a default issue template
- Add a support template
=> docs: Add additional github template files.

build.gradle
This reverts commit 823ac7fc1d636dbbaafc0bac2a5500cb66a98962.
=> chore: revert "build(gradle): Bump spark_version from 3.4.1 to 3.5.0 …"

build.gradle
=> chore: revert "build(gradle): Bump spark_version from 3.4.1 to 3.5.0"

build.gradle
This reverts commit f3d0f1bf125d93f1ba1284bbbf1097f5f1e4e486.
=> chore: revert "build(gradle): Bump spark_version from 3.4.1 to 3.5.0 (#349)"
